version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependencies"]
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependencies"]
    open-pull-requests-limit: 5
    groups:
      front:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependencies"]
    groups:
      docker:
        patterns: ["*"]
